cas_server.settings:
  type: config_object
  label: 'CAS Server settings'
  mapping:
    ticket:
      type: mapping
      label: 'Ticket Timeout Settings'
      mapping:
        service_ticket_timeout:
          type: integer
          label: 'Service Ticket Timeout (seconds)'
        proxy_ticket_timeout:
          type: integer
          label: 'Proxy Ticket Timeout (seconds)'
        proxy_granting_ticket_timeout:
          type: integer
          label: 'Proxy Granting Ticket Timeout (seconds)'
        ticket_granting_ticket_timeout:
          type: integer
          label: 'Ticket Granting Ticket Timeout (seconds)'
        ticket_granting_ticket_auth:
          type: boolean
          label: 'Whether to use a ticket granting cookie'

    messages:
      type: mapping
      label: 'Custom Messages'
      mapping:
        invalid_service:
          type: string
          label: 'Display Message for Invalid Service'
        user_logout:
          type: string
          label: 'Display Message for User Logout'
        logged_in:
          type: string
          label: 'Display Message for Logged In Users'

    debugging:
      type: mapping
      label: 'Debugging Options'
      mapping:
        log:
          type: boolean
          label: 'Enable debugging log'

cas_server.cas_server_service.*:
  type: config_entity
  label: 'Service definitions'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    service:
      type: string
      label: 'Service URL pattern'
    sso:
      type: boolean
      label: 'Enable SSO'
    attributes:
      type: sequence
      label: 'Released attributes'
      sequence:
        type: string
            
